CREATE TABLE playlists (
id UUID PRIMARY KEY,
name varchar(80) NOT NULL,
description TEXT,
is_public BOOLEAN NOT NULL,
image_url TEXT,
user_id UUID  NOT NULL REFERENCES users(id) ON DELETE CASCADE,


created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)