CREATE TABLE songs(

id UUID PRIMARY KEY,
title varchar(100) NOT NULL,
artist varchar (80) NOT NULL,
song_url TEXT NOT NULL,
image_url TEXT NOT NULL,
user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,


created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

